#!/usr/bin/env python3
"""
============================================================
MAKE-OG-IMAGES — link preview cards, one per league
------------------------------------------------------------
Regenerates og-image.png in the league accent colour. These are
what Discord, iMessage and Slack show when somebody pastes a link.

    python3 tools/make-og-images.py

Writes:
    og-image.png                  the root redirect page
    scbthunderdome/og-image.png   the league page

Both cards are identical today — the root is a redirect, not a
picker, so there is no "set of leagues" for it to represent. They
are kept as two files because each page's <meta> points at its own
absolute URL, which is what makes a deep link preview correctly.

FONTS
    The site uses Oswald and JetBrains Mono from Google Fonts.
    Neither ships with this image pipeline, so the closest
    metric-compatible substitutes are used instead:
        Oswald         -> Liberation Sans Narrow Bold
        JetBrains Mono -> DejaVu Sans Mono Bold
    All three cards are generated by this same script, so they
    match each other exactly. If you ever want true Oswald,
    install the TTF and point DISPLAY_FONT at it, then re-run —
    all three regenerate together and stay consistent.

Requires Pillow.  pip install pillow
============================================================
"""

from PIL import Image, ImageDraw, ImageFont
import os

W, H = 1200, 630

NAVY_DEEP = (6, 11, 22)
NAVY_PANEL = (16, 29, 51)
CHALK = (242, 244, 248)
STEEL = (127, 139, 163)

DISPLAY_FONT = "/usr/share/fonts/truetype/liberation/LiberationSansNarrow-Bold.ttf"
MONO_FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf"

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")

# Sampled from the State College Borough mark: the arched sky and
# the hills. BLUE is the site accent; GREEN is decorative only, and
# is deliberately kept away from the win-green the site uses for
# results. See PER-LEAGUE ACCENTS in style.css.
BLUE = (58, 169, 201)
GREEN = (63, 163, 77)

# (folder, tagline, subline, accent, chips)
CARDS = [
    ("",               "ONLINE DYNASTY", "SCHEDULE  ·  POWER RANKINGS  ·  ROSTER", BLUE, [BLUE, GREEN]),
    ("scbthunderdome", "ONLINE DYNASTY", "SCHEDULE  ·  POWER RANKINGS  ·  ROSTER", BLUE, [BLUE, GREEN]),
]


def blend(c1, c2, t):
    return tuple(round(a + (b - a) * t) for a, b in zip(c1, c2))


def build(tag, subline, accent, chips):
    img = Image.new("RGB", (W, H), NAVY_DEEP)
    d = ImageDraw.Draw(img, "RGBA")

    # Vertical wash, deep at the bottom like the site background.
    for y in range(H):
        d.line([(0, y), (W, y)], fill=blend((13, 22, 38), NAVY_DEEP, y / H))

    # Lighter wedge on the left, cut on the diagonal — the same angled
    # language as the panels and buttons on the site.
    #
    # Built as its own gradient and pasted through a polygon mask.
    # Stacking translucent polygons instead looks fine for two or three
    # and then compounds: at 70 layers the "faint" tint had built up
    # into a solid olive slab.
    wedge = Image.new("RGB", (W, H))
    wd = ImageDraw.Draw(wedge)
    for y in range(H):
        t = y / H
        # Warm dark at the top, fading to the page navy by the bottom.
        wd.line([(0, y), (W, y)], fill=blend(blend(accent, NAVY_PANEL, 0.86), NAVY_DEEP, t))

    mask = Image.new("L", (W, H), 0)
    ImageDraw.Draw(mask).polygon([(0, 0), (390, 0), (215, H), (0, H)], fill=255)
    img.paste(wedge, (0, 0), mask)

    # Faint diagonal pinstripes across the whole card.
    for x in range(-H, W + H, 46):
        d.line([(x, 0), (x + H, H)], fill=(255, 255, 255, 5), width=1)

    d.rectangle([0, 0, W, 4], fill=accent)                       # top rule
    d.polygon([(W, H), (W, H - 120), (W - 120, H)], fill=accent)  # corner flag

    f_badge = ImageFont.truetype(MONO_FONT, 25)
    f_tag = ImageFont.truetype(MONO_FONT, 31)

    # Shrink the subline until it clears the right margin instead of
    # trusting a hand-picked size. The strings are configurable at the
    # top of this file, so a longer one must not silently run off the
    # card - which is exactly what happened at 26px.
    TEXT_X, RIGHT_MARGIN = 608, 56
    for pt in range(26, 13, -1):
        f_sub = ImageFont.truetype(MONO_FONT, pt)
        if TEXT_X + d.textlength(subline, font=f_sub) <= W - RIGHT_MARGIN:
            break
    else:
        print(f"  WARNING: subline still overflows at {pt}pt")

    # Badge, top right — a parallelogram matching .league-badge.
    label = "EA COLLEGE FOOTBALL 27"
    tw = d.textlength(label, font=f_badge)
    bx2, by1, by2 = W - 78, 88, 138
    bx1 = bx2 - tw - 44
    d.polygon(
        [(bx1 + 14, by1), (bx2, by1), (bx2 - 14, by2), (bx1, by2)], fill=accent
    )
    d.text((bx1 + 22, by1 + 10), label, font=f_badge, fill=NAVY_DEEP)

    # The reversed lockup: dome plus white wordmark, already knocked
    # out and clipped by tools/make-logo-assets.py. Rendering that
    # asset beats reproducing the knockout here - an earlier version
    # flood filled the white backing away at card build time, which
    # worked but had to be cropped above the ground band or it ate the
    # windows. Doing it once, in the logo pipeline, is safer.
    lockup = None
    try:
        import cairosvg, io
        png = cairosvg.svg2png(
            url=os.path.join(ROOT, "logo-reverse.svg"), output_width=1400)
        lockup = Image.open(io.BytesIO(png)).convert("RGBA")
        lockup.thumbnail((470, 470), Image.LANCZOS)
    except Exception as e:
        print(f"  (logo-reverse.svg not rendered: {e}; text only card)")

    if lockup is not None:
        img.paste(lockup, (96, (H - lockup.height) // 2 - 20), lockup)


    d.text((TEXT_X, 268), tag, font=f_tag, fill=CHALK)
    d.text((TEXT_X, 320), subline, font=f_sub, fill=STEEL)

    # Two angled chips in the mark's two colours — a small nod to the
    # borough logo without trying to redraw it at this size.
    for i, c in enumerate(chips):
        x = TEXT_X + i * 58
        d.polygon([(x + 8, 372), (x + 46, 372), (x + 38, 386), (x, 386)], fill=c)

    return img


def main():
    import sys

    # Both cards are generated by this script from scratch, so there is
    # no hand-made original to preserve the way the NCAA Legends repo
    # had. The flag is accepted and ignored so old muscle memory and
    # any copied command still work.
    _ = "--include-main" in sys.argv

    for d_name, tag, subline, accent, chips in CARDS:
        out_dir = os.path.join(ROOT, d_name) if d_name else ROOT
        os.makedirs(out_dir, exist_ok=True)
        out = os.path.join(out_dir, "og-image.png")
        build(tag, subline, accent, chips).save(out, optimize=True)
        size = os.path.getsize(out) / 1024
        print(f"  {out.replace(ROOT + os.sep, ''):24} {size:6.1f} KB  {tag}")


if __name__ == "__main__":
    main()
